apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: semblend-trtllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: "gp3"
